sudo: false
language: php
php:
  - '5.6'
env:
  - NON_INTERACTIVE=true
before_install:
  - composer self-update
  - nvm install 4.2.4
  - nvm use 4.2.4
  - npm install -g grunt-cli
  - npm --version
  - node --version
  - npm list -g
install:
  - npm install
  - php src/lib/pre-install.php --non-interactive
script:
  - npm test